/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;
import java.lang.Math;

/**
 *
 * @author nithy
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Scientific_Calculator
     */
    public Calculator() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        res_label = new javax.swing.JLabel();
        Input_label = new javax.swing.JLabel();
        Input = new javax.swing.JTextField();
        _1 = new javax.swing.JButton();
        _2 = new javax.swing.JButton();
        _3 = new javax.swing.JButton();
        _4 = new javax.swing.JButton();
        _5 = new javax.swing.JButton();
        _6 = new javax.swing.JButton();
        _7 = new javax.swing.JButton();
        _8 = new javax.swing.JButton();
        _9 = new javax.swing.JButton();
        _0 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        negative = new javax.swing.JButton();
        multi = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        total = new javax.swing.JButton();
        point = new javax.swing.JButton();
        mod = new javax.swing.JButton();
        Result = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scientific Calculator");
        setBounds(new java.awt.Rectangle(100, 100, 483, 298));

        res_label.setText(" Result :");

        Input_label.setText("Input :");

        Input.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Input.setToolTipText("Enter the value");
        Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputActionPerformed(evt);
            }
        });

        _1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        _1.setText("1");
        _1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _1ActionPerformed(evt);
            }
        });

        _2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        _2.setText("2");
        _2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _2ActionPerformed(evt);
            }
        });

        _3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        _3.setText("3");
        _3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _3ActionPerformed(evt);
            }
        });

        _4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        _4.setText("4");
        _4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _4ActionPerformed(evt);
            }
        });

        _5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        _5.setText("5");
        _5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _5ActionPerformed(evt);
            }
        });

        _6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        _6.setText("6");
        _6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _6ActionPerformed(evt);
            }
        });

        _7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        _7.setText("7");
        _7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _7ActionPerformed(evt);
            }
        });

        _8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        _8.setText("8");
        _8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _8ActionPerformed(evt);
            }
        });

        _9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        _9.setText("9");
        _9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _9ActionPerformed(evt);
            }
        });

        _0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        _0.setText("0");
        _0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _0ActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clear.setText("C");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        plus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        negative.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        negative.setText("-");
        negative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negativeActionPerformed(evt);
            }
        });

        multi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        multi.setText("*");
        multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiActionPerformed(evt);
            }
        });

        divide.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        divide.setText("/");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });

        total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        total.setText("=");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        point.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        point.setText(".");
        point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointActionPerformed(evt);
            }
        });

        mod.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mod.setText("%");
        mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modActionPerformed(evt);
            }
        });

        Result.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Result.setToolTipText("Enter the value");
        Result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Input_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Input)
                                .addGap(6, 6, 6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(_3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(_4)
                                .addGap(18, 18, 18)))
                        .addComponent(res_label))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(_5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(_6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(_7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(_0)
                                .addGap(11, 11, 11)
                                .addComponent(point, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_8)
                            .addComponent(clear))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(negative, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(multi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mod)
                            .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Result))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(res_label)
                    .addComponent(Input_label)
                    .addComponent(Input, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(point, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clear)
                            .addComponent(_9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(negative, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(multi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mod, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int operator;
    private void InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputActionPerformed

    private void _1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__1ActionPerformed
        // TODO add your handling code here:
        String a;
        a=Input.getText();
        Input.setText(a+"1");
    }//GEN-LAST:event__1ActionPerformed

    private void _2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__2ActionPerformed
        // TODO add your handling code here:
        String a;
        a=Input.getText();
        Input.setText(a+"2");
    }//GEN-LAST:event__2ActionPerformed

    private void _3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__3ActionPerformed
        // TODO add your handling code here:
        String a;
        a=Input.getText();
        Input.setText(a+"3");
    }//GEN-LAST:event__3ActionPerformed

    private void _4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__4ActionPerformed
        // TODO add your handling code here:
        String a;
        a=Input.getText();
        Input.setText(a+"4");
    }//GEN-LAST:event__4ActionPerformed

    private void _5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__5ActionPerformed
        // TODO add your handling code here:
        String a;
        a=Input.getText();
        Input.setText(a+"5");
    }//GEN-LAST:event__5ActionPerformed

    private void _6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__6ActionPerformed
        // TODO add your handling code here:
        String a;
        a=Input.getText();
        Input.setText(a+"6");
    }//GEN-LAST:event__6ActionPerformed

    private void _7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__7ActionPerformed
        // TODO add your handling code here:
        String a;
        a=Input.getText();
        Input.setText(a+"7");
    }//GEN-LAST:event__7ActionPerformed

    private void _8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__8ActionPerformed
        // TODO add your handling code here:
        String a;
        a=Input.getText();
        Input.setText(a+"8");
    }//GEN-LAST:event__8ActionPerformed

    private void _9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__9ActionPerformed
        // TODO add your handling code here:
        String a;
        a=Input.getText();
        Input.setText(a+"9");
    }//GEN-LAST:event__9ActionPerformed

    private void _0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__0ActionPerformed
        // TODO add your handling code here:
        String a;
        a=Input.getText();
        Input.setText(a+"0");
    }//GEN-LAST:event__0ActionPerformed

    private void pointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointActionPerformed
        // TODO add your handling code here:
        String a;
        a=Input.getText();
        Input.setText(a+".");
    }//GEN-LAST:event_pointActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        Input.setText("");
        Result.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        // TODO add your handling code here:
        String a;
        a=Input.getText();
        Input.setText(a+"+");
        operator=1;
    }//GEN-LAST:event_plusActionPerformed

    private void negativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negativeActionPerformed
        // TODO add your handling code here:
        String a;
        a=Input.getText();
        Input.setText(a+"-");
        operator=2;
    }//GEN-LAST:event_negativeActionPerformed

    private void multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiActionPerformed
        // TODO add your handling code here:
        String a;
        a=Input.getText();
        Input.setText(a+"*");
        operator=3;
    }//GEN-LAST:event_multiActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        // TODO add your handling code here:
        String a;
        a=Input.getText();
        Input.setText(a+"/");
        operator=4;
    }//GEN-LAST:event_divideActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
        String a;
        a=Input.getText();
        String b[]=new String[2];
        Double n1,n2;
        switch(operator)
        {
            case 1: b=a.split("\\+");
                    n1=Double.parseDouble(b[0]);
                    n2=Double.parseDouble(b[1]);
                    Result.setText(String.valueOf(n1+n2));
                    break;
            case 2: b=a.split("-");
                    n1=Double.parseDouble(b[0]);
                    n2=Double.parseDouble(b[1]);
                    Result.setText(String.valueOf(n1-n2));
                    break;
            case 3: b=a.split("\\*");
                    n1=Double.parseDouble(b[0]);
                    n2=Double.parseDouble(b[1]);
                    Result.setText(String.valueOf(n1*n2));
                    break;
            case 4: b=a.split("/");
                    n1=Double.parseDouble(b[0]);
                    n2=Double.parseDouble(b[1]);
                    if(n2==0)
                        Result.setText("Not possible");
                    else
                        Result.setText(String.valueOf(n1/n2));
                    break;
            case 5: b=a.split("%");
                    n1=Double.parseDouble(b[0]);
                    n2=Double.parseDouble(b[1]);
                    Result.setText(String.valueOf(n1%n2));
        }
    }//GEN-LAST:event_totalActionPerformed

    private void modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modActionPerformed
        // TODO add your handling code here:
        String a;
        a=Input.getText();
        Input.setText(a+"%");
        operator=5;
    }//GEN-LAST:event_modActionPerformed

    private void ResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Input;
    private javax.swing.JLabel Input_label;
    private javax.swing.JTextField Result;
    private javax.swing.JButton _0;
    private javax.swing.JButton _1;
    private javax.swing.JButton _2;
    private javax.swing.JButton _3;
    private javax.swing.JButton _4;
    private javax.swing.JButton _5;
    private javax.swing.JButton _6;
    private javax.swing.JButton _7;
    private javax.swing.JButton _8;
    private javax.swing.JButton _9;
    private javax.swing.JButton clear;
    private javax.swing.JButton divide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mod;
    private javax.swing.JButton multi;
    private javax.swing.JButton negative;
    private javax.swing.JButton plus;
    private javax.swing.JButton point;
    private javax.swing.JLabel res_label;
    private javax.swing.JButton total;
    // End of variables declaration//GEN-END:variables
}
